
# Uncomment the next line to define a global platform for your project
platform :ios, '14'

target 'Playlet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Playlet
    #remote network pods

    pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']


    pod 'Moya'
    pod 'Alamofire'
    pod 'ReactiveSwift'
    pod 'RxSwift'
    
    pod 'SDWebImageSwiftUI'
    pod 'StarStream'


    pod "SVGAPlayer"
    pod "QGVAPlayer"

    pod 'NIMSDK_LITE' # 云信
    # pod 'ZegoExpressEngine' # 即构
    # pod 'VolcEngineRTC' # 火山的RTC库，稍后再加入
    pod 'SnapKit' # 约束库
    pod 'SwiftyFitsize'  # 适配库
    
    pod 'FCUUID' #添加唯一的设备码
    pod 'HandyJSON'

  target 'PlayletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlayletUITests' do
    # Pods for testing
  end

end
